# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DatingApp3' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DatingApp3
  pod 'Parse'
  pod 'AlamofireImage'
  pod 'MessageInputBar'

  target 'DatingApp3Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DatingApp3UITests' do
    # Pods for testing
  end

end
